"""add date_range to construction_notices

Revision ID: bd7c76480677
Revises: 106813781e8f
Create Date: 2025-11-08 09:26:33.633706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7c76480677'
down_revision: Union[str, Sequence[str], None] = '106813781e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction_notices', sa.Column('date_range', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('construction_notices', 'date_range')
    # ### end Alembic commands ###
