"""change id type

Revision ID: c0d182a9159f
Revises: fb96429bf303
Create Date: 2025-11-08 17:06:41.784720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d182a9159f'
down_revision: Union[str, Sequence[str], None] = 'fb96429bf303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###
