"""add user favorite

Revision ID: fb96429bf303
Revises: ebdc06235afa
Create Date: 2025-11-08 16:59:09.032593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb96429bf303'
down_revision: Union[str, Sequence[str], None] = 'ebdc06235afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('place_data', sa.JSON(), nullable=True),
    sa.Column('road_name', sa.String(length=500), nullable=True),
    sa.Column('road_search_name', sa.String(length=500), nullable=True),
    sa.Column('road_osmids', sa.JSON(), nullable=True),
    sa.Column('road_distance_threshold', sa.Float(), nullable=True),
    sa.Column('route_start', sa.String(length=500), nullable=True),
    sa.Column('route_end', sa.String(length=500), nullable=True),
    sa.Column('route_start_coords', sa.JSON(), nullable=True),
    sa.Column('route_end_coords', sa.JSON(), nullable=True),
    sa.Column('route_distance', sa.Float(), nullable=True),
    sa.Column('route_duration', sa.Float(), nullable=True),
    sa.Column('route_feature_collection', sa.JSON(), nullable=True),
    sa.Column('route_distance_threshold', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('distance_threshold', sa.Float(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
